fos_rest:
  service:
    serializer: "fos_rest.serializer.jms"
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: ~, prefer_extension: false }
    #media_type:
    #    version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'

  body_converter:
    enabled: true
    validate: true

  view:
    empty_content: 200
    view_response_listener: 'force'
    failed_validation: HTTP_BAD_REQUEST
    formats:
      json: true
      xml: false
    templating_formats:
      html: true

  exception:
    enabled: true
    exception_controller: 'App\Controller\Base\ErrorController::showAction'
    codes:
      'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
      'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': 405
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  routing_loader:
    default_format: json