jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            app:
                namespace_prefix: App
                path: "%kernel.project_dir%/config/serializer/App"
        warmup:
            paths:
                included: ["%kernel.project_dir%/src/Entity"]
