<?php


namespace App\Controller\Api;

use App\Controller\Base\BaseController;
use App\Entity\Product;
use App\Forms\Product\ProductForm;
use App\Service\ProductService\ProductServiceInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Rest\Route("/products")
 */
class ProductController extends BaseController
{
	protected $formPost = ProductForm::class;
	protected $formUpdate = ProductForm::class;
	protected $entityClass = Product::class;

	public function __construct(ProductServiceInterface $service)
	{
		$this->service = $service;
	}

	/**
	 * @Rest\Get("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function collection(Request $request)
	{
		return parent::collection($request);
	}

	/**
	 * @Rest\Get("/{slug}")
	 * @param string $slug
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function item(string $slug)
	{
		return parent::item($slug); // TODO: Change the autogenerated stub
	}

	/**
	 * @Rest\Delete("/{slug}")
	 * @param string $slug
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function delete(string $slug)
	{
		return parent::delete($slug);
	}

	/**
	 * @Rest\Post("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function post(Request $request)
	{
		return parent::post($request);
	}

	/**
	 * @Rest\Patch("/{slug}")
	 * @param Request $request
	 * @param string $slug
	 * @param string $method
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function patch(Request $request, string $slug, string $method = Request::METHOD_PATCH)
	{
		return parent::update($request, $slug, $method);
	}

	/**
	 * @Rest\Put("/{slug}")
	 * @param Request $request
	 * @param string $slug
	 * @param string $method
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function put(Request $request, string $slug, string $method = Request::METHOD_PATCH)
	{
		return parent::update($request, $slug, $method);
	}

	/**
	 * @Rest\Get("/{slug}/comments")
	 * @param Product $product
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function collectionCommentsByBrand(Product $product, Request $request)
	{
		return parent::collectionRelation($request, $product, 'getCommentsProducts');
	}
}