<?php


namespace App\Controller\Api;

use App\Controller\Base\BaseController;
use App\Entity\User;
use App\Forms\User\RegisterForm;
use App\Forms\User\UpdateForm;
use App\Service\UserService\UserServiceInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Rest\Route("/users")
 * Class UserController
 * @package App\Controller
 */
class UserController extends BaseController
{
	protected $formPost = RegisterForm::class;
	protected $formUpdate = UpdateForm::class;
	protected $entityClass = User::class;
	protected $groupItem = 'user:item';
	protected $groupCollection = 'user:collection';
	protected $groupUpdate = 'user:update';

	public function __construct(UserServiceInterface $service)
	{
		$this->service = $service;
	}

	/**
	 * @Rest\Get("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function collection(Request $request)
	{
		return parent::collection($request);
	}

	/**
	 * @Rest\Post("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function post(Request $request)
	{
		return parent::post($request);
	}

	/**
	 * @Rest\Get("/{slug}")
	 * @param $slug
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function item(string $slug)
	{
		return parent::item($slug); // TODO: Change the autogenerated stub
	}

	/**
	 * @Rest\Delete("/{slug}")
	 * @param $slug
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function delete(string $slug)
	{
		return parent::delete($slug);
	}

	/**
	 * @Rest\Patch("/{slug}")
	 * @param Request $request
	 * @param string $slug
	 */
	public function patch(Request $request, string $slug)
	{
		return parent::update($request, $slug,  Request::METHOD_PATCH);
	}

	/**
	 * @Rest\Put("/{slug}")
	 * @param Request $request
	 * @param string $slug
	 */
	public function put(Request $request, string $slug)
	{
		return parent::update($request, $slug,  Request::METHOD_PUT);
	}
}