<?php


namespace App\Controller\Api;

use App\Controller\Base\BaseController;
use App\Entity\User;
use App\Forms\User\RegisterForm;
use App\Service\UserService\UserServiceInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Rest\Route("/users")
 * Class UserController
 * @package App\Controller
 */
class UserController extends BaseController
{
	protected $formPost = RegisterForm::class;
	protected $entityClass = User::class;

	public function __construct(UserServiceInterface $service)
	{
		$this->service = $service;
	}

	/**
	 * @Rest\Get("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function collectionGet(Request $request)
	{
		$this->service->checkRights(null, ['method' => 'collection']);
		return parent::collectionGet($request);
	}

	/**
	 * @Rest\Post("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function post(Request $request)
	{
		return parent::post($request);
	}

	/**
	 * @Rest\Get("/{slug}")
	 * @param $slug
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function item($slug)
	{
		return parent::item($slug); // TODO: Change the autogenerated stub
	}
}